### ISSUE TITLE
Message-relayer-fast stopped due to MessageRelayerService._getStateBatchHeader error

### ISSUE THREAD

**Issue by cby3149** [omgnetwork/optimism#162]
{"level":50,"time":1625456689806,"extra":{"message":"TypeError: Cannot read property 'data' of null","stack":"TypeError: Cannot read property 'data' of null\n    at MessageRelayerService._getStateBatchHeader (/opt/optimism-message-relayer-fast/dist/service.js:201:128)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async MessageRelayerService._isTransactionFinalized (/opt/optimism-message-relayer-fast/dist/service.js:215:24)\n    at async MessageRelayerService._start (/opt/optimism-message-relayer-fast/dist/service.js:109:23)\n    at async MessageRelayerService.start (/opt/optimism-message-relayer-fast/node_modules/@eth-optimism/common-ts/dist/base-service.js:33:9)\n    at async main (/opt/optimism-message-relayer-fast/dist/exec/run.js:89:5)\n    at async /opt/optimism-message-relayer-fast/exec/r

**Comment by cby3149** [comment]
I added `this.logger.info` to the message-relayer-fast to help us debug.

**Comment by cby3149** [comment]
{"level":30,"time":1626589816741,"msg":"Checking for newly finalized transactions..."}
{"level":30,"time":1626589816741,"height":6228,"msg":"Checking if tx is finalized"}
{"level":30,"time":1626589816752,"startingBlock":8956000,"endBlock":8958000,"msg":"Querying events"}
{"level":30,"time":1626589816887,"event":{"blockNumber":8956595,"blockHash":"0xa0ddd447560eda51d7792987e24efb68a64f932fd96cc4bdb7b3bff99057044e","transactionIndex":13,"removed":false,"address":"0x1ba99640444B81f3928e4F174CFB4FF426B4FFAE","data":"0xad8dc011d344abc26e13d8baa0a6b88724d2d093f2a3761dafc43ef28fec3b3d00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000001854000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000060f3c0470000000000000000000000007f3cdbe9906fd57373e8d18aaa159fc713f379b0","topics":["0x16be4c5129a4e03cf3350262e181dc02ddfb4a6008d925368c0899fcd97ca9c5","0x00000000000000000000000000000000000000000000000000000000000008bd"],"transactionHash":"0x96509977129070bc041a2b5c367c5a2f7f524d388afd64fe575873e326ec67c1","logIndex":31,"event":"StateBatchAppended","eventSignature":"StateBatchAppended(uint256,bytes32,uint256,uint256,bytes)","args":[{"type":"BigNumber","hex":"0x08bd"},"0xad8dc011d344abc26e13d8baa0a6b88724d2d093f2a3761dafc43ef28fec3b3d",{"type":"BigNumber","hex":"0x02"},{"type":"BigNumber","hex":"0x1854"},"0x0000000000000000000000000000000000000000000000000000000060f3c0470000000000000000000000007f3cdbe9906fd57373e8d18aaa159fc713f379b0"]},"msg":"Got state batch appended event"}
{"level":30,"time":1626589816908,"transaction":null,"msg":"Got event transaction"}
{"level":50,"time":1626589816908,"extra":{"message":"TypeError: Cannot read property 'data' of null","stack":"TypeError: Cannot read property 'data' of null\n    at MessageRelayerService._getStateBatchHeader (/opt/optimism/packages/omgx/message-relayer-fast/dist/service.js:207:128)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async MessageRelayerService._isTransactionFinalized (/opt/optimism/packages/omgx/message-relayer-fast/dist/service.js:221:24)\n    at async MessageRelayerService._start (/opt/optimism/packages/omgx/message-relayer-fast/dist/service.js:109:23)\n    at async MessageRelayerService.start (/opt/optimism/packages/common-ts/dist/base-service.js:33:9)\n    at async main (/opt/optimism/packages/omgx/message-relayer-fast/dist/exec/run.js:89:5)\n    at async /opt/optimism/packages/omgx/message-relayer-fast/exec/run-message-relayer-fast.js:6:3"},"msg":"Caught an unhandled error"}

**Comment by cby3149** [comment]
Fixed.
