### ISSUE TITLE
Fraud Prover Docker image (latest) currently broken

### ISSUE THREAD

**Issue by CAPtheorem** [omgnetwork/optimism#30]
Will wait 37 more times for http://verifier:8045 to be up...

Connected to L2 Verifier Node at http://verifier:8045

internal/modules/cjs/loader.js:888

throw err;

^

Error: Cannot find module 'ethers'

Require stack:

- /opt/fraud-prover/dist/exec/run.js

- /opt/fraud-prover/exec/run.js

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)

at Function.Module._load (internal/modules/cjs/loader.js:730:27)

at Module.require (internal/modules/cjs/loader.js:957:19)

at require (internal/modules/cjs/helpers.js:88:18)

at Object.<anonymous> (/opt/fraud-prover/dist/exec/run.js:3:18)

at Module._compile (internal/modules/cjs/loader.js:1068:30)

at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)

at Module.load (internal/modules/cjs/loader.js:933:32)

at Function.Module._load (internal/modules/cjs/loader.js:774:14)

at Module.require (internal/modules/cjs/loader.js:957:19) {

code: 'MODULE_NOT_FOUND',

requireStack: [

'/opt/fraud-prover/dist/exec/run.js',

'/opt/fraud-prover/exec/run.js'

]

}

**Comment by CAPtheorem** [comment]
Fixed
