### ISSUE TITLE
[batch-submitter] Sequencer transaction timestamp exceeds that of next queue element.

### ISSUE THREAD

**Issue by cby3149** [omgnetwork/optimism#65]

**Comment by CAPtheorem** [comment]
I think this was addressed - see if the problem is still there

**Comment by cby3149** [comment]
The production side has this issue again. 
```
{"level":50,"time":1625264851509,"name":"oe:batch_submitter:tx_chain","extra":{"index":25,"expected":1625222120,"got":1625222121},"msg":"Observed mismatched values"}
{"level":50,"time":1625264851510,"extra":{"message":"TypeError: (intermediate value) is not iterable","stack":"TypeError: (intermediate value) is not iterable\n    at TransactionBatchSubmitter._submitBatch (/opt/optimism/packages/batch-submitter/src/batch-submitter/tx-batch-submitter.ts:234:7)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at loop (/opt/optimism/packages/batch-submitter/src/exec/run-batch-submitter.ts:442:9)"},"msg":"Unhandled exception during batch submission"}
```
From my understanding, the batch submitter compares the timestamp and block number of the L1 chain and data in `OVM_ChainStorageContainer-CTC-queue`.
Question:
* Who pushed data to `OVM_ChainStorageContainer-CTC-queue`?
* Why the timestamp and block number are different?
